### ISSUE TITLE
Tensor-board will override the logs directory

### ISSUE THREAD

**Issue by CodeProcessor** [CodeProcessor/DeepLab-Training-Pipeline#2]
When training multiple times, tensor-board will override the logs directory. Can we add the time to logs directory?

![image](https://user-images.githubusercontent.com/24785073/135765334-f54e83d9-0ea8-471c-adde-a0bca305efb0.png)

**Comment by Tehara-Fonseka** [comment]
addressed Issue: https://github.com/ultralytics/yolov5/issues/5034#issue-1014301362

**Comment by CodeProcessor** [comment]
Closing the issue since its already fixed in the recent pull request - https://github.com/CodeProcessor/DeepLab-Training-Pipeline/pull/3
